// Generated by CoffeeScript 1.7.1
(function() {
  var error, log, makeMarker, options, success;

  console.log("Hello world");

  options = {
    enableHighAccuracy: true,
    timeout: 5000,
    maximumAge: 0
  };

  success = function(pos) {
    var crd, http, params, url;
    crd = pos.coords;
    console.log('Your current position is:');
    console.log('Latitude : ' + crd.latitude);
    console.log('Longitude: ' + crd.longitude);
    console.log('More or less ' + crd.accuracy + ' meters.');
    http = new XMLHttpRequest();
    url = "https://secret-about-box.herokuapp.com/sendLocation";
    params = "login=EricDapper&lat=" + crd.latitude + "&lng=" + crd.longitude + "&message=Hello%20World";
    console.log(params);
    http.open("POST", url, true);
    http.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
    http.onreadystatechange = function() {
      var location, locations, _i, _len, _results;
      if (http.readyState === 4 && http.status === 200) {
        console.log(http.responseText);
        locations = JSON.parse(http.responseText);
        _results = [];
        for (_i = 0, _len = locations.length; _i < _len; _i++) {
          location = locations[_i];
          _results.push(makeMarker(window.map, location.lat, location.lng, "<h3>User: " + location.login + "</h3><p>Message: " + location.message + "<p>"));
        }
        return _results;
      }
    };
    return http.send(params);
  };

  error = function(error) {
    return console.warn(error);
  };

  log = function(text) {
    return console.log(text);
  };

  makeMarker = function(map, lat, lng, title) {
    var infowindow, marker;
    marker = new google.maps.Marker({
      position: new google.maps.LatLng(lat, lng),
      title: title
    });
    marker.setMap(map);
    infowindow = new google.maps.InfoWindow();
    return google.maps.event.addListener(marker, 'click', function() {
      infowindow.setContent(marker.title);
      return infowindow.open(map, marker);
    });
  };

  window.init = function(test) {
    var landmark, myOptions;
    landmark = new google.maps.LatLng(42.3599611, -71.0567528);
    myOptions = {
      zoom: 13,
      center: landmark,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    window.map = new google.maps.Map(document.getElementById("map"), myOptions);
    return navigator.geolocation.getCurrentPosition(success, error, options);
  };

}).call(this);
