// Generated by CoffeeScript 1.7.1
(function() {
  var error, options, success;

  console.log("Hello world");

  options = {
    enableHighAccuracy: true,
    timeout: 5000,
    maximumAge: 0
  };

  success = function(pos) {
    var crd;
    crd = pos.coords;
    console.log('Your current position is:');
    console.log('Latitude : ' + crd.latitude);
    console.log('Longitude: ' + crd.longitude);
    return console.log('More or less ' + crd.accuracy + ' meters.');
  };

  error = function(error) {
    return console.warn(error);
  };

  navigator.geolocation.getCurrentPosition(success, error, options);

}).call(this);
