// Generated by CoffeeScript 1.7.1
(function() {
  window.parse = function() {
    var request;
    request = new XMLHttpRequest();
    request.onreadystatechange = function() {
      var messageArray, messages, msg, _i, _len, _results;
      if (request.readyState === 4 && request.status === 200) {
        messageArray = JSON.parse(request.responseText);
        messages = document.getElementById("messages");
        _results = [];
        for (_i = 0, _len = messageArray.length; _i < _len; _i++) {
          msg = messageArray[_i];
          _results.push(messages.innerHTML += "<div class=\"msg\"><span class=\"content\">\"" + msg.content + "\"</span><span class=\"author\">" + msg.username + "</span></div>");
        }
        return _results;
      }
    };
    request.open('GET', 'http://messagehub.herokuapp.com/messages.json', true);
    request.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
    return request.send(null);
  };

}).call(this);
